export const books = [
  {
    id: 1,
    title: 'Harry Potter and the Philosopher\'s Stone',
    pages: 223,
    genre: 'Fantasy',
  },
  {
    id: 2,
    title: 'Harry Potter and the Chamber of Secrets',
    pages: 251,
    genre: 'Fantasy',
  },
  {
    id: 3,
    title: 'Harry Potter and the Prisoner of Azkaban',
    pages: 317,
    genre: 'Fantasy',
  },
  {
    id: 4,
    title: 'Harry Potter and the Goblet of Fire',
    pages: 636,
    genre: 'Fantasy',
  },
  {
    id: 5,
    title: 'Harry Potter and the Order of the Phoenix',
    pages: 766,
    genre: 'Fantasy',
  },
  {
    id: 6,
    title: 'Harry Potter and the Half-Blood Prince',
    pages: 607,
    genre: 'Fantasy',
  },
  {
    id: 7,
    title: 'Harry Potter and the Deathly Hallows',
    pages: 607,
    genre: 'Fantasy',
  },
  {
    id: 8,
    title: 'The Fellowship of the Ring',
    pages: 423,
    genre: 'Fantasy',
  },
  {
    id: 9,
    title: 'The Two Towers',
    pages: 352,
    genre: 'Fantasy',
  },
  {
    id: 10,
    title: 'The Return of the King',
    pages: 416,
    genre: 'Fantasy',
  },
  {
    id: 11,
    title: 'A Game of Thrones',
    pages: 835,
    genre: 'Fantasy',
  },
  {
    id: 12,
    title: 'A Clash of Kings',
    pages: 766,
    genre: 'Fantasy',
  },
  {
    id: 13,
    title: 'A Storm of Swords',
    pages: 973,
    genre: 'Fantasy',
  },
  {
    id: 14,
    title: 'A Feast for Crows',
    pages: 753,
    genre: 'Fantasy',
  },
  {
    id: 15,
    title: 'A Dance with Dragons',
    pages: 1016,
    genre: 'Fantasy',
  },
  {
    id: 16,
    title: 'The Name of the Wind',
    pages: 662,
    genre: 'Fantasy',
  },
  {
    id: 17,
    title: 'The Wise Man\'s Fear',
    pages: 100,
    genre: 'Fantasy',
  },
  {
    id: 18,
    title: 'American Gods',
    pages: 465,
    genre: 'Fantasy',
  },
  {
    id: 19,
    title: 'Stardust',
    pages: 208,
    genre: 'Fantasy',
  },
  {
    id: 20,
    title: 'Neverwhere',
    pages: 480,
    genre: 'Fantasy',
  },
  {
    id: 21,
    title: 'Good Omens',
    pages: 416,
    genre: 'Fantasy',
  },
  {
    id: 22,
    title: 'The Ocean at the End of the Lane',
    pages: 208,
    genre: 'Fantasy',
  },
  {
    id: 23,
    title: 'The Graveyard Book',
    pages: 304,
    genre: 'Fantasy',
  },
  {
    id: 24,
    title: 'The Ocean at the End of the Lane',
    pages: 208,
    genre: 'Fantasy',
  },
  {
    id: 25,
    title: 'The Graveyard Book',
    pages: 304,
    genre: 'Fantasy',
  },
  {
    id: 26,
    title: 'The Sandman',
    pages: 304,
    genre: 'Fantasy',
  },
  {
    id: 27,
    title: 'The Sandman: The Doll\'s House',
    pages: 304,
    genre: 'Fantasy',
  },
  {
    id: 28,
    title: 'The Sandman: Dream Country',
    pages: 304,
    genre: 'Fantasy',
  },
  {
    id: 29,
    title: 'The Sandman: Season of Mists',
    pages: 304,
    genre: 'Fantasy',
  },
  {
    id: 30,
    title: 'The Sandman: Fables and Reflections',
    pages: 304,
    genre: 'Fantasy',
  },
  {
    id: 31,
    title: 'The Sandman: World\'s End',
    pages: 304,
    genre: 'Fantasy',
  },
  {
    id: 32,
    title: 'The Sandman: Brief Lives',
    pages: 304,
    genre: 'Fantasy',
  },
  {
    id: 33,
    title: 'The Sandman: The Kindly Ones',
    pages: 304,
    genre: 'Fantasy',
  },
  {
    id: 34,
    title: 'The Sandman: The Wake',
    pages: 304,
    genre: 'Fantasy',
  },
  {
    id: 35,
    title: 'The Sandman: Endless Nights',
    pages: 304,
    genre: 'Fantasy',
  },
  {
    id: 36,
    title: 'The Sandman: The Doll\'s House',
    pages: 304,
    genre: 'Fantasy',
  },
  {
    id: 37,
    title: 'The Sandman: Dream Country',
    pages: 304,
    genre: 'Fantasy',
  },
  {
    id: 38,
    title: 'The Sandman: Season of Mists',
    pages: 304,
    genre: 'Fantasy',
  },
]
